name: DocAssist CI Workflow

on:
  push:
    branches:
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and publish with Maven
        run: |
          VERSION=$(./build/create-semver.sh pom.xml "${{github.run_number}}-$GITHUB_SHA")
          mvn -B versions:set -DnewVersion="${VERSION}" --file pom.xml
          mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
