name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make script executable
        run: chmod +x ./build/create-semver.sh
      - name: Build and publish with Maven
        run: |
          VERSION=$(./build/create-semver.sh DocAssist/pom.xml "4")
          mvn -B versions:set -DnewVersion="${VERSION}" --file DocAssist/pom.xml
          mvn -B deploy --file DocAssist/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
